#!/bin/sh
# ───────────────────────────────────────────────────────────
# AlertManager Entrypoint
# ───────────────────────────────────────────────────────────
# Generates alertmanager.yml at startup:
#   - If SLACK_WEBHOOK_URL is set: config with Slack receiver
#   - Otherwise: console-only config
#   - Validates config before starting AlertManager
# ───────────────────────────────────────────────────────────
set -e

CONFIG_FILE="/etc/alertmanager/alertmanager.yml"

if [ -n "${SLACK_WEBHOOK_URL}" ]; then
  # ── WITH SLACK INTEGRATION ─────────────────────────────
  echo "Enabling Slack notifications to: ${SLACK_CHANNEL:-#monitoring-alerts}"
  cat > "$CONFIG_FILE" << EOF
# AlertManager Configuration — PRLedger Monitoring
# Auto-generated by entrypoint.sh

route:
  receiver: "default"
  group_by: ["alertname", "severity"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  routes:
    - match:
        severity: critical
      receiver: "default"
      repeat_interval: 1h
    - match:
        severity: warning
      receiver: "default"
      repeat_interval: 4h
    - match:
        severity: info
      receiver: "default"
      repeat_interval: 8h

receivers:
  - name: "default"
    slack_configs:
      - api_url: "${SLACK_WEBHOOK_URL}"
        channel: "${SLACK_CHANNEL}"
        send_resolved: true
        title: '{{ template "slack.title" . }}'
        text: '{{ template "slack.text" . }}'

inhibit_rules:
  - source_match:
      severity: "critical"
    target_match:
      severity: "warning"
    equal: ["alertname"]

templates:
  - "/etc/alertmanager/templates/*.tmpl"
EOF

else
  # ── CONSOLE ONLY (no Slack) ────────────────────────────
  echo "Slack not configured. Alerts will be logged to console."
  cat > "$CONFIG_FILE" << 'EOF'
# AlertManager Configuration — PRLedger Monitoring
# Auto-generated by entrypoint.sh

route:
  receiver: "default"
  group_by: ["alertname", "severity"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  routes:
    - match:
        severity: critical
      receiver: "default"
      repeat_interval: 1h
    - match:
        severity: warning
      receiver: "default"
      repeat_interval: 4h
    - match:
        severity: info
      receiver: "default"
      repeat_interval: 8h

receivers:
  - name: "default"

inhibit_rules:
  - source_match:
      severity: "critical"
    target_match:
      severity: "warning"
    equal: ["alertname"]
EOF
fi

# ── Validate config ──────────────────────────────────────
echo "Validating AlertManager config..."
/bin/alertmanager --config.file="$CONFIG_FILE" --test.config 2>&1 || {
  echo "ERROR: AlertManager config validation failed!"
  echo "--- Generated config ---"
  cat "$CONFIG_FILE"
  exit 1
}

echo "Validation passed. Starting AlertManager..."

# ── Start AlertManager ───────────────────────────────────
exec /bin/alertmanager \
  --config.file="$CONFIG_FILE" \
  --storage.path="/alertmanager" \
  --log.level="${ALERTMANAGER_LOG_LEVEL:-info}"
