<template>
  <div class="ai-review-results">
    <!-- Disclaimer -->
    <div class="ai-disclaimer" data-theme-disclaimer>
      <strong>⚠️ Disclaimer:</strong> This review result was generated by AI and may not be fully accurate. Please verify all important information independently.
    </div>

    <!-- Summary Stats -->
    <div v-if="suggestions.summary" class="ai-summary-stats">
      <div class="ai-stat-card">
        <div class="ai-stat-value ai-stat-files">{{ suggestions.summary.files_reviewed || 0 }}</div>
        <div class="ai-stat-label">Files Reviewed</div>
      </div>
      <div class="ai-stat-card">
        <div class="ai-stat-value ai-stat-critical">{{ suggestions.summary.critical_count || 0 }}</div>
        <div class="ai-stat-label">Critical Issues</div>
      </div>
      <div class="ai-stat-card">
        <div class="ai-stat-value ai-stat-total">{{ suggestions.summary.total_issues || 0 }}</div>
        <div class="ai-stat-label">Total Issues</div>
      </div>
    </div>

    <!-- Issues List -->
    <div v-if="issues.length > 0" class="ai-issues-list">
      <div
        v-for="(issue, index) in issues"
        :key="index"
        class="ai-issue-item"
        :class="`severity-${issue.severity}`"
      >
        <div class="ai-issue-header">
          <span class="ai-issue-number">#Issue {{ index + 1 }}</span>
          <span class="ai-issue-file">📄 {{ issue.file }}</span>
          <span v-if="issue.line" class="ai-issue-line">
            Line {{ issue.line }}
          </span>
        </div>
        
        <div class="issue-badges">
          <el-tag :type="getCategoryColor(issue.category)" size="small" effect="plain">
            {{ issue.category.toUpperCase() }}
          </el-tag>
          <el-tag 
            :style="{ 
              backgroundColor: getSeverityBackgroundColor(issue.severity),
              borderColor: getSeverityBorderColor(issue.severity),
              color: getSeverityTextColor(issue.severity)
            }" 
            size="small"
          >
            {{ issue.severity.toUpperCase() }}
          </el-tag>
        </div>

        <div v-if="issue.description" class="ai-issue-section">
          <h5 class="ai-section-title">📝 Description</h5>
          <div class="ai-section-content ai-issue-description">
            <p>{{ issue.description }}</p>
          </div>
        </div>

        <div v-if="issue.suggestion" class="ai-issue-section">
          <h5 class="ai-section-title">💡 Suggestion</h5>
          <div class="ai-section-content ai-issue-suggestion">
            <p>{{ issue.suggestion }}</p>
          </div>
        </div>

        <div v-if="issue.code_snippet" class="ai-issue-section">
          <h5 class="ai-section-title">💻 Code Snippet</h5>
          <div class="ai-section-content ai-issue-code">
            <pre><code>{{ issue.code_snippet }}</code></pre>
          </div>
        </div>
      </div>
    </div>

    <el-empty v-else description="✅ No issues found! Great code!" />

    <!-- Positive Feedback -->
    <div v-if="suggestions.positive_feedback && suggestions.positive_feedback.length > 0" class="ai-issue-section">
      <h5 class="ai-section-title">✅ Positive Feedback</h5>
      <div class="ai-section-content ai-positive-feedback">
        <ul>
          <li v-for="(feedback, index) in suggestions.positive_feedback" :key="index">
            {{ feedback }}
          </li>
        </ul>
      </div>
    </div>

    <!-- Overall Assessment -->
    <div v-if="suggestions.overall_assessment" class="ai-issue-section">
      <h5 class="ai-section-title">📊 Overall Assessment</h5>
      <div class="ai-section-content ai-overall-assessment">
        <p>{{ suggestions.overall_assessment }}</p>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import type { AIReviewSuggestions, AIReviewIssue } from '@/api/reviews'
import { useTheme } from '@/composables/useTheme'

const props = defineProps<{
  suggestions: AIReviewSuggestions
}>()

const { currentTheme } = useTheme()

const isDarkTheme = computed(() => {
  if (currentTheme.value === 'auto') {
    return window.matchMedia('(prefers-color-scheme: dark)').matches
  }
  return currentTheme.value === 'dark'
})

const issues = computed(() => props.suggestions.issues || [])

const getSeverityColor = (severity: string) => {
  const colors: Record<string, any> = {
    critical: 'danger',
    high: 'warning',
    medium: 'info',
    low: 'success',
  }
  return colors[severity] || 'info'
}

const getCategoryColor = (category: string) => {
  const colors: Record<string, any> = {
    bug: 'danger',
    security: 'danger',
    performance: 'warning',
    style: 'info',
    maintainability: 'info',
    architecture: '',
  }
  return colors[category.toLowerCase()] || 'info'
}

// Severity color helpers to match border colors
const getSeverityBackgroundColor = (severity: string): string => {
  if (isDarkTheme.value) {
    const colors: Record<string, string> = {
      critical: '#7f1d1d',
      high: '#7c2d12',
      medium: '#713f12',
      low: '#1e3a8a',
    }
    return colors[severity] || '#1e293b'
  }
  
  const colors: Record<string, string> = {
    critical: '#fee2e2',
    high: '#ffedd5',
    medium: '#fef9c3',
    low: '#dbeafe',
  }
  return colors[severity] || '#f1f5f9'
}

const getSeverityBorderColor = (severity: string): string => {
  if (isDarkTheme.value) {
    const colors: Record<string, string> = {
      critical: '#fca5a5',
      high: '#fdba74',
      medium: '#fde047',
      low: '#60a5fa',
    }
    return colors[severity] || '#475569'
  }
  
  const colors: Record<string, string> = {
    critical: '#ef4444',
    high: '#f97316',
    medium: '#eab308',
    low: '#3b82f6',
  }
  return colors[severity] || '#cbd5e1'
}

const getSeverityTextColor = (severity: string): string => {
  if (isDarkTheme.value) {
    const colors: Record<string, string> = {
      critical: '#fecaca',
      high: '#fed7aa',
      medium: '#fef08a',
      low: '#bfdbfe',
    }
    return colors[severity] || '#e2e8f0'
  }
  
  const colors: Record<string, string> = {
    critical: '#991b1b',
    high: '#9a3412',
    medium: '#854d0e',
    low: '#1e40af',
  }
  return colors[severity] || '#475569'
}
</script>

<style scoped>
.ai-review-results {
  padding: 15px;
}

.ai-disclaimer {
  background: #fef3c7;
  border-left: 4px solid #f59e0b;
  padding: 12px;
  border-radius: 6px;
  margin-bottom: 15px;
  font-size: 0.85rem;
  color: #92400e;
}

[data-theme='dark'] .ai-disclaimer {
  background: #451a03;
  color: #fbbf24;
  border-left-color: #f59e0b;
}

.ai-summary-stats {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 10px;
  margin-bottom: 15px;
}

.ai-stat-card {
  background: white;
  padding: 12px;
  border-radius: 6px;
  text-align: center;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
  border: 2px solid var(--el-border-color);
}

[data-theme='dark'] .ai-stat-card {
  background: #1e293b;
  border-color: #334155;
}

.ai-stat-value {
  font-size: 1.5rem;
  font-weight: 800;
  margin-bottom: 4px;
}

.ai-stat-critical { color: #ef4444; }
.ai-stat-total { color: #f59e0b; }
.ai-stat-files { color: #3b82f6; }

[data-theme='dark'] .ai-stat-critical { color: #fca5a5; }
[data-theme='dark'] .ai-stat-total { color: #fbbf24; }
[data-theme='dark'] .ai-stat-files { color: #60a5fa; }

.ai-stat-label {
  font-size: 0.75rem;
  color: var(--el-text-color-secondary);
  font-weight: 600;
  text-transform: uppercase;
}

.ai-issues-list {
  margin-top: 15px;
}

.ai-issue-item {
  background: white;
  border: 2px solid var(--el-border-color);
  border-radius: 8px;
  padding: 12px;
  margin-bottom: 10px;
  transition: all 0.3s;
}

[data-theme='dark'] .ai-issue-item {
  background: #1e293b;
  border-color: #334155;
}

.ai-issue-item:hover {
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
  transform: translateX(3px);
}

/* Severity-based border colors */
.ai-issue-item.severity-critical {
  border-left: 4px solid #ef4444;
}

.ai-issue-item.severity-high {
  border-left: 4px solid #f97316;
}

.ai-issue-item.severity-medium {
  border-left: 4px solid #eab308;
}

.ai-issue-item.severity-low {
  border-left: 4px solid #3b82f6;
}

[data-theme='dark'] .ai-issue-item.severity-critical {
  border-left-color: #fca5a5;
}

[data-theme='dark'] .ai-issue-item.severity-high {
  border-left-color: #fdba74;
}

[data-theme='dark'] .ai-issue-item.severity-medium {
  border-left-color: #fde047;
}

[data-theme='dark'] .ai-issue-item.severity-low {
  border-left-color: #60a5fa;
}

.ai-issue-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 8px;
  flex-wrap: wrap;
  gap: 8px;
}

.ai-issue-number {
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  color: white;
  padding: 4px 12px;
  border-radius: 12px;
  font-size: 0.85rem;
  font-weight: 700;
  box-shadow: 0 2px 4px rgba(102, 126, 234, 0.3);
}

[data-theme='dark'] .ai-issue-number {
  background: linear-gradient(135deg, #8b5cf6 0%, #a78bfa 100%);
}

.ai-issue-file {
  font-weight: 700;
  color: var(--el-text-color-primary);
  font-size: 0.9rem;
}

.ai-issue-line {
  background: #f1f5f9;
  padding: 3px 10px;
  border-radius: 12px;
  font-size: 0.8rem;
  font-weight: 600;
  color: var(--el-text-color-secondary);
}

[data-theme='dark'] .ai-issue-line {
  background: #334155;
  color: #cbd5e1;
}

.issue-badges {
  display: flex;
  gap: 8px;
  margin-bottom: 12px;
}

/* Issue Section - Title and Content Separation */
.ai-issue-section {
  margin-bottom: 15px;
}

.ai-section-title {
  font-size: 1.05rem;
  font-weight: 700;
  color: var(--el-text-color-primary);
  margin: 0 0 8px 0;
  padding-bottom: 6px;
  border-bottom: 2px solid var(--el-border-color-lighter);
}

.ai-section-content {
  padding: 10px;
  border-radius: 6px;
  font-size: 0.9rem;
  line-height: 1.6;
}

.ai-issue-description {
  background: #f8fafc;
  border-left: 3px solid #3b82f6;
  color: var(--text-secondary);
}

[data-theme='dark'] .ai-issue-description {
  background: #0f172a;
  border-left-color: #60a5fa;
  color: #cbd5e1;
}

.ai-issue-suggestion {
  background: #f0fdf4;
  border-left: 3px solid #22c55e;
  color: #166534;
}

[data-theme='dark'] .ai-issue-suggestion {
  background: #064e3b;
  border-left-color: #6ee7b7;
  color: #6ee7b7;
}

.ai-issue-description p,
.ai-issue-suggestion p {
  margin: 0;
  color: inherit;
}

.ai-issue-code {
  background: #1e293b;
  color: #e2e8f0;
  padding: 10px;
  border-radius: 6px;
  overflow-x: auto;
  margin: 0;
}

.ai-issue-code pre {
  margin: 0;
  font-size: 0.85rem;
  line-height: 1.5;
  background: transparent;
  color: inherit;
}

.ai-issue-code code {
  font-family: 'SF Mono', 'Monaco', 'Inconsolata', monospace;
}

.ai-positive-feedback {
  background: #f0fdf4;
  border-left: 3px solid #22c55e;
}

[data-theme='dark'] .ai-positive-feedback {
  background: #064e3b;
  border-left-color: #6ee7b7;
}

.ai-positive-feedback ul {
  margin: 0;
  padding-left: 20px;
}

.ai-positive-feedback li {
  margin: 4px 0;
  line-height: 1.6;
  color: var(--el-text-color-primary);
  font-size: 0.9rem;
}

.ai-overall-assessment {
  background: #eff6ff;
  border-left: 3px solid #2563eb;
  font-size: 0.9rem;
  line-height: 1.6;
  color: var(--el-text-color-primary);
}

[data-theme='dark'] .ai-overall-assessment {
  background: #1e3a8a;
  border-left-color: #3b82f6;
  color: #bfdbfe;
}

.ai-overall-assessment p {
  margin: 0;
  color: inherit;
}
</style>
