from __future__ import annotations

from datetime import UTC, datetime
from typing import TYPE_CHECKING

from sqlalchemy import Boolean, DateTime, Index, Integer, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from src.core.database import Base


if TYPE_CHECKING:
    from src.models.pull_request import PullRequestReview, PullRequestScore


class User(Base):
    """User model representing the user table in the database"""

    __tablename__ = "user"

    # Primary key - auto-generated by database
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True, index=True)

    # Business ID - passed by API caller (e.g., GitHub user ID)
    user_id: Mapped[int] = mapped_column(Integer, unique=True, nullable=False, index=True)

    # User information
    username: Mapped[str] = mapped_column(String(64), unique=True, nullable=False, index=True)

    display_name: Mapped[str] = mapped_column(String(128), nullable=False)

    email_address: Mapped[str] = mapped_column(String(255), unique=True, nullable=False, index=True)

    # Status fields
    active: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)

    is_reviewer: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)

    # Timestamps
    created_date: Mapped[datetime] = mapped_column(
        DateTime, nullable=False, default=lambda: datetime.now(UTC)
    )

    updated_date: Mapped[datetime] = mapped_column(
        DateTime,
        nullable=False,
        default=lambda: datetime.now(UTC),
        onupdate=lambda: datetime.now(UTC),
    )

    # Relationships
    authored_reviews: Mapped[list[PullRequestReview]] = relationship(
        foreign_keys="PullRequestReview.pull_request_user", back_populates="pull_request_user_rel"
    )

    reviewed_reviews: Mapped[list[PullRequestReview]] = relationship(
        foreign_keys="PullRequestReview.reviewer", back_populates="reviewer_rel"
    )

    # Score records given by this user
    scores_given: Mapped[list[PullRequestScore]] = relationship(
        foreign_keys="PullRequestScore.reviewer", back_populates="reviewer_rel"
    )

    # Indexes
    __table_args__ = (
        Index("idx_username", "username"),
        Index("idx_email", "email_address"),
    )

    def __repr__(self) -> str:
        """String representation of the user"""
        return (
            f"<User(id={self.id}, username='{self.username}', "
            f"display_name='{self.display_name}', email='{self.email_address}')>"
        )

    def to_dict(self) -> dict:
        """Convert user model to dictionary"""
        return {
            "id": self.id,
            "user_id": self.user_id,
            "username": self.username,
            "display_name": self.display_name,
            "email_address": self.email_address,
            "active": self.active,
            "is_reviewer": self.is_reviewer,
            "created_date": self.created_date.isoformat() if self.created_date else None,
            "updated_date": self.updated_date.isoformat() if self.updated_date else None,
        }

    @classmethod
    def from_dict(cls, data: dict) -> User:
        """Create user instance from dictionary"""
        return cls(
            username=data.get("username"),
            display_name=data.get("display_name"),
            email_address=data.get("email_address"),
            active=data.get("active", True),
            is_reviewer=data.get("is_reviewer", False),
        )

    def update(self, data: dict) -> None:
        """Update user attributes from dictionary"""
        for key, value in data.items():
            if hasattr(self, key) and key not in ["id", "created_date"]:
                setattr(self, key, value)
